# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Supernatural Language Processing
description:      'We blog about natural language processing and machine learning.'
baseurl:	  /

github:
  repo:           https://github.com/supernlp/supernlp.github.io

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: supernlp

