# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Supernatural Language Final
tagline:          'A Jekyll theme'
description:      'We blog about NLP and machine learning'
baseurl:          ''

paginate:         5

