# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Supernatural Language Hargle_3
tagline:          'A Jekyll theme'
description:      'We blog about NLP and machine learning'
baseurl:          'asdqwe/'

paginate:         5

