# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Supernatural Language Hargle_3
tagline:          'A Jekyll theme'
description:      'We blog about NLP and machine learning'
baseurl:          /

paginate:         5

