# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Supernatural Language Processing
description:      'We blog about NLP and machine learning'
baseurl:          ''

paginate:         20

github:
  repo:           https://github.com/supernlp/supernlp.github.io
